# config/meta.yml
meta_product_name: "Trusty"
meta_title: "Trusty - Aplicación de servicios de confianza"
meta_description: "Encuentra profesionales confiables cerca de ti. Trusty conecta personas con servicios verificados para que contrates con tranquilidad."
meta_image: "bannertrusty.png" 
